server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VictorSosa-dev/demo-microservice
          default-label: 03-eureka
          skipSslValidation: true
          search-paths: config-data
  application:
    name: config-service